#!/usr/bin/env python3
"""
merge-codex-config.py — ensure OUR Bedrock provider in ~/.codex/config.toml
without clobbering a user-supplied config.

Codex is fully config-driven (model providers, MCP servers, profiles, AGENTS.md).
A user can upload their own config.toml, but it must NOT override how we reach the
model: inference goes through Amazon Bedrock, authenticated by the microVM IAM
role. Which Bedrock endpoint depends on the model, and the model registry
(config/models.json, DL-033) is what knows:

  bedrock-runtime  the inference-profile ids (us.openai.gpt-…) on
                   https://bedrock-runtime.<region>.amazonaws.com/openai/v1,
                   no OpenAI-Project header
  bedrock-mantle   the bare ids (openai.gpt-…) on
                   https://bedrock-mantle.<region>.api.aws/openai/v1, which
                   REQUIRES OpenAI-Project ("Engine not found" without it)

So we treat the provider wiring as ours and everything else (mcp_servers,
profiles, prefs) as theirs: strip any top-level key we own and EITHER
[model_providers.bedrock-*] section from their file — switching endpoints has to
remove the other endpoint's stale block — then emit ours first and theirs after.
The bearer token is NOT written here: it is an env var (`OPENAI_API_KEY`)
referenced via `env_key`, minted fresh per run.

What "ours" IS — the keys and the provider tables — is generated by
`models_registry.codex_config_fragment`, one generator with two callers: this
merger, and the fleet runtime's local-fallback config writer. This file owns the
merge (what survives from the user's config, and in which order), nothing more.

Config reference: https://developers.openai.com/codex/config-file/config-reference

Usage: merge-codex-config.py <config.toml> <model> <base_url> <endpoint> \
                             [project] [context_window]
Writes the merged file back in place (creates it if absent).
"""
import re
import sys

# Unguarded: models_registry.py is always co-located (the Dockerfile lands both in
# /app, and this script runs as /app/merge-codex-config.py), and a missing twin
# must fail loudly rather than silently write a different provider block.
from models_registry import (
    CODEX_DEFAULT_CONTEXT_WINDOW as DEFAULT_CONTEXT_WINDOW,
    CODEX_DEFAULT_PROJECT as DEFAULT_PROJECT,
    codex_config_fragment,
)

ENDPOINTS = ("bedrock-runtime", "bedrock-mantle")

# The top-level keys we own. A `model =` inside a [profiles.*] table is the
# user's and must survive — only the pre-first-header block is ours. Re-stripped
# on every merge so our own keys never duplicate.
OURS_TOP_LEVEL_RE = re.compile(
    r"^\s*(model|model_provider|model_context_window|model_max_output_tokens"
    r"|web_search)\s*="
)


def split_user_config(existing: str) -> tuple[str, str]:
    """Split the user's file into (top-level keys, [table] blocks), dropping
    every key and section we own."""
    top: list[str] = []
    tables: list[str] = []
    skip_section = False
    in_top_level = True  # before the first [section] header
    for line in existing.splitlines():
        stripped = line.strip()
        if stripped.startswith("["):
            in_top_level = False
            # Enter/exit EITHER of our provider sections (and their subtables).
            # Deliberately not endpoint-specific: a session that moves from
            # mantle to bedrock-runtime must not leave the old provider behind.
            skip_section = stripped.startswith("[model_providers.bedrock-")
            if skip_section:
                continue
        if skip_section:
            continue
        if in_top_level and OURS_TOP_LEVEL_RE.match(line):
            continue
        (top if in_top_level else tables).append(line)
    return "\n".join(top).strip(), "\n".join(tables).strip()


def our_fragment(model: str, base_url: str, endpoint: str, project: str,
                 context_window: int) -> tuple[str, str]:
    """Our (top-level keys, provider tables) for one endpoint.

    The fragment itself lives in the byte-identical models_registry.py twin, so
    the fleet runtime's local-fallback writer emits the same provider block this
    merger does; there is nothing left here but the delegation.
    """
    return codex_config_fragment(model, base_url, endpoint, project, context_window)


def merge(existing: str, model: str, base_url: str, endpoint: str, project: str,
          context_window: int) -> str:
    """Our keys, then the user's surviving top-level keys, then our tables, then
    the user's tables.

    The order matters and used to be wrong: emitting the user's surviving
    top-level keys AFTER our [model_providers.…] header silently turned their
    `approval_policy = "never"` into a key of OUR provider table.
    """
    user_top, user_tables = split_user_config(existing)
    ours_top, ours_tables = our_fragment(model, base_url, endpoint, project,
                                         context_window)
    blocks = [b for b in (ours_top, user_top, ours_tables, user_tables) if b]
    return "\n\n".join(blocks) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 4:
        sys.stderr.write(
            "usage: merge-codex-config.py <config.toml> <model> <base_url> "
            "<endpoint> [project] [context_window]\n")
        return 2
    path, model, base_url, endpoint = argv[:4]
    project = (argv[4] if len(argv) > 4 else "") or DEFAULT_PROJECT
    if endpoint not in ENDPOINTS:
        sys.stderr.write(f"merge-codex-config: unknown endpoint {endpoint!r} "
                         f"(want one of {', '.join(ENDPOINTS)})\n")
        return 2
    raw_ctx = argv[5] if len(argv) > 5 else ""
    context_window = DEFAULT_CONTEXT_WINDOW
    if raw_ctx.strip():
        try:
            context_window = int(raw_ctx.strip())
            if context_window <= 0:
                raise ValueError(raw_ctx)
        except ValueError:
            sys.stderr.write(f"merge-codex-config: bad context_window {raw_ctx!r} "
                             f"— using {DEFAULT_CONTEXT_WINDOW}\n")
            context_window = DEFAULT_CONTEXT_WINDOW

    try:
        with open(path) as f:
            existing = f.read()
    except FileNotFoundError:
        existing = ""

    with open(path, "w") as f:
        f.write(merge(existing, model, base_url, endpoint, project, context_window))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
