#!/bin/bash
#
# setup-coding-efs.sh — provision the VPC + EFS the coding runtime mounts.
#
# Deploys cfn-vpc-efs.yaml (VPC, subnets, NAT, SG, EFS, access point, mount
# targets) and writes the outputs to deploy/coding-agent-runtime/efs.config,
# which deploy.py sources to wire the runtime into VPC mode with EFS at /mnt/efs.
#
# Idempotent: re-runs update the stack. All values STS/env-derived.
#
# Usage:
#   export AWS_PROFILE=<your-profile>
#   bash deploy/coding-agent-runtime/setup-coding-efs.sh

set -e

REGION="${AWS_REGION:-us-east-1}"
STACK="agentcore-hub-coding-vpc-efs"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE="$SCRIPT_DIR/cfn-vpc-efs.yaml"
OUT_CONFIG="$SCRIPT_DIR/efs.config"

echo "   Deploying CloudFormation stack: $STACK (region $REGION)"
aws cloudformation deploy \
  --region "$REGION" \
  --stack-name "$STACK" \
  --template-file "$TEMPLATE" \
  --capabilities CAPABILITY_IAM \
  --no-fail-on-empty-changeset

echo "   Fetching stack outputs..."
get_out() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue | [0]" --output text
}

VPC_ID=$(get_out VpcId)
SUBNET_1=$(get_out PrivateSubnet1Id)
SUBNET_2=$(get_out PrivateSubnet2Id)
SECURITY_GROUP=$(get_out SecurityGroupId)
EFS_FS_ID=$(get_out EFSFileSystemId)
EFS_AP_ARN=$(get_out EFSAccessPointArn)

cat > "$OUT_CONFIG" <<EOF
# Generated by setup-coding-efs.sh — sourced by deploy.py.
export CODING_VPC_ID="$VPC_ID"
export CODING_SUBNET_1="$SUBNET_1"
export CODING_SUBNET_2="$SUBNET_2"
export CODING_SECURITY_GROUP="$SECURITY_GROUP"
export CODING_EFS_FILESYSTEM_ID="$EFS_FS_ID"
export CODING_EFS_ACCESS_POINT_ARN="$EFS_AP_ARN"
EOF

echo "   ✓ EFS infra ready. Outputs → $OUT_CONFIG"
echo "       VPC:          $VPC_ID"
echo "       Subnets:      $SUBNET_1, $SUBNET_2"
echo "       SG:           $SECURITY_GROUP"
echo "       EFS:          $EFS_FS_ID"
echo "       AccessPoint:  $EFS_AP_ARN"
