"use client";

import { useEffect, useRef, useState, useCallback } from "react";
import { X, Download } from "lucide-react";

/**
 * Full-screen image viewer with pinch-zoom, double-tap-to-zoom, and pan.
 * Mobile-first: a tapped artifact thumbnail opens here so you can inspect a
 * screenshot/mockup at full size. Tap the backdrop or × to close.
 *
 * Touch model:
 *  - one finger drag (while zoomed) → pan
 *  - two-finger pinch → zoom about the pinch midpoint
 *  - double-tap → toggle 1× ⇄ 2.5×
 * Mouse: wheel to zoom, drag to pan (while zoomed), double-click → toggle
 * 1× ⇄ 2.5×.
 *
 * Panning (mouse and touch) is clamped so the image never leaves the
 * viewport: once an edge of the scaled image reaches the matching viewport
 * edge the offset stops there, and axes where the scaled image still fits
 * inside the viewport stay centered.
 */

const DRAG_THRESHOLD_PX = 5; // movement below this counts as a click, not a drag
export default function Lightbox({
  src,
  alt,
  downloadName,
  onClose,
}: {
  src: string;
  alt?: string;
  downloadName?: string;
  onClose: () => void;
}) {
  const [scale, setScale] = useState(1);
  const [tx, setTx] = useState(0);
  const [ty, setTy] = useState(0);
  // Rendered state only (cursor grab/grabbing); gesture bookkeeping stays in refs.
  const [dragging, setDragging] = useState(false);

  const imgRef = useRef<HTMLImageElement | null>(null);

  // Gesture state kept in refs so handlers don't churn on every move.
  const gesture = useRef<{
    mode: "none" | "pan" | "pinch" | "drag";
    startX: number;
    startY: number;
    startTx: number;
    startTy: number;
    startDist: number;
    startScale: number;
    moved: boolean;
  }>({
    mode: "none",
    startX: 0,
    startY: 0,
    startTx: 0,
    startTy: 0,
    startDist: 0,
    startScale: 1,
    moved: false,
  });
  const lastTap = useRef(0);
  // True between the double-tap toggle (second touchstart) and its touchend;
  // that touchend calls preventDefault() so the browser doesn't synthesize a
  // click/dblclick pair from the two taps — the synthesized dblclick would
  // hit onDoubleClick and immediately toggle the zoom straight back.
  const doubleTapHandled = useRef(false);
  // When the last touchend happened; onDoubleClick ignores dblclicks arriving
  // right after touch activity in case a browser synthesizes one anyway.
  const lastTouchEndAt = useRef(0);
  // True while the click generated by a just-finished drag is still pending.
  const dragClickPending = useRef(false);
  // Whether each of the last two clicks came out of a drag; a double-click
  // whose presses include a drag must not toggle zoom.
  const lastTwoClicksDragged = useRef<[boolean, boolean]>([false, false]);

  const reset = useCallback(() => {
    setScale(1);
    setTx(0);
    setTy(0);
  }, []);

  /**
   * Clamp a pan offset so the image can't be dragged out of the viewport.
   * Per axis: if the scaled image fits inside the viewport it stays centered
   * (offset 0); otherwise the offset is limited so the image edge stops at
   * the viewport edge — |offset| <= (scaledDim − viewportDim) / 2, since the
   * translate applies to a centered element. Layout size comes from
   * offsetWidth/offsetHeight (untransformed, so independent of the current
   * scale); the container is fixed inset-0, so the viewport is the window.
   */
  const clampOffset = useCallback((x: number, y: number, s: number) => {
    const img = imgRef.current;
    if (!img) return { x, y };
    const clampAxis = (offset: number, layoutDim: number, viewportDim: number) => {
      const scaledDim = layoutDim * s;
      if (scaledDim <= viewportDim) return 0;
      const max = (scaledDim - viewportDim) / 2;
      return Math.min(max, Math.max(-max, offset));
    };
    return {
      x: clampAxis(x, img.offsetWidth, window.innerWidth),
      y: clampAxis(y, img.offsetHeight, window.innerHeight),
    };
  }, []);

  // Close on Escape; lock body scroll while open.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    document.addEventListener("keydown", onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  // Re-clamp when the viewport changes (resize, orientation rotate): the
  // permitted offsets shrink with the viewport, and an image panned to the old
  // limit would otherwise show blank space past its edge until the next
  // pan/zoom runs clampOffset.
  useEffect(() => {
    const reclamp = () => {
      const c = clampOffset(tx, ty, scale);
      if (c.x !== tx) setTx(c.x);
      if (c.y !== ty) setTy(c.y);
    };
    window.addEventListener("resize", reclamp);
    window.addEventListener("orientationchange", reclamp);
    return () => {
      window.removeEventListener("resize", reclamp);
      window.removeEventListener("orientationchange", reclamp);
    };
  }, [tx, ty, scale, clampOffset]);

  const dist = (t: React.TouchList) =>
    Math.hypot(t[0].clientX - t[1].clientX, t[0].clientY - t[1].clientY);

  const onTouchStart = (e: React.TouchEvent) => {
    const g = gesture.current;
    if (e.touches.length === 2) {
      g.mode = "pinch";
      g.startDist = dist(e.touches);
      g.startScale = scale;
      g.startTx = tx;
      g.startTy = ty;
      // A pinch is not a tap: disarm the double-tap detector so a quick tap
      // right after the pinch can't pair with its first finger-down and
      // spuriously toggle the zoom.
      lastTap.current = 0;
    } else if (e.touches.length === 1) {
      // Double-tap detection.
      const now = Date.now();
      if (now - lastTap.current < 300) {
        setScale((s) => (s > 1 ? 1 : 2.5));
        if (scale > 1) reset();
        lastTap.current = 0;
        doubleTapHandled.current = true;
        return;
      }
      lastTap.current = now;
      g.mode = "pan";
      g.startX = e.touches[0].clientX;
      g.startY = e.touches[0].clientY;
      g.startTx = tx;
      g.startTy = ty;
      g.moved = false;
    }
  };

  const onTouchMove = (e: React.TouchEvent) => {
    const g = gesture.current;
    if (g.mode === "pinch" && e.touches.length === 2) {
      e.preventDefault();
      const next = Math.min(5, Math.max(1, (dist(e.touches) / g.startDist) * g.startScale));
      setScale(next);
      if (next === 1) {
        setTx(0);
        setTy(0);
      } else {
        // Re-clamp at the intermediate scale so zooming out while panned
        // never leaves the image stranded outside the viewport.
        const c = clampOffset(tx, ty, next);
        setTx(c.x);
        setTy(c.y);
      }
    } else if (g.mode === "pan" && e.touches.length === 1) {
      const dx = e.touches[0].clientX - g.startX;
      const dy = e.touches[0].clientY - g.startY;
      if (!g.moved && Math.hypot(dx, dy) >= DRAG_THRESHOLD_PX) {
        g.moved = true;
        // A real pan must not arm the double-tap detector: without this, the
        // next tap would pair with this gesture's start and toggle zoom.
        lastTap.current = 0;
      }
      if (scale > 1) {
        e.preventDefault();
        const c = clampOffset(g.startTx + dx, g.startTy + dy, scale);
        setTx(c.x);
        setTy(c.y);
      }
    }
  };

  const onTouchEnd = (e: React.TouchEvent) => {
    gesture.current.mode = "none";
    lastTouchEndAt.current = Date.now();
    if (doubleTapHandled.current) {
      doubleTapHandled.current = false;
      // The double-tap already toggled the zoom in onTouchStart; stop the
      // browser from synthesizing the tap's click/dblclick. (React attaches
      // touchend non-passively, so this preventDefault is honored.)
      e.preventDefault();
    }
  };

  // Desktop: wheel zoom.
  const onWheel = (e: React.WheelEvent) => {
    const next = Math.min(5, Math.max(1, scale - e.deltaY * 0.003));
    setScale(next);
    if (next === 1) {
      setTx(0);
      setTy(0);
    } else {
      // Keep the current pan inside bounds at the new scale (see onTouchMove).
      const c = clampOffset(tx, ty, next);
      setTx(c.x);
      setTy(c.y);
    }
  };

  // Desktop: drag-to-pan via pointer events. Pointer events also fire for
  // touch, so every handler bails unless pointerType is "mouse" — the touch
  // handlers above keep full ownership of pinch/pan/double-tap behavior.
  const onPointerDown = (e: React.PointerEvent) => {
    if (e.pointerType !== "mouse" || e.button !== 0 || scale <= 1) return;
    const g = gesture.current;
    g.mode = "drag";
    g.startX = e.clientX;
    g.startY = e.clientY;
    g.startTx = tx;
    g.startTy = ty;
    g.moved = false;
    setDragging(true);
    // Capture so fast drags that leave the image keep tracking (jsdom and
    // older environments may not implement pointer capture — skip quietly).
    try {
      imgRef.current?.setPointerCapture?.(e.pointerId);
    } catch {
      /* pointer capture unavailable */
    }
  };

  const onPointerMove = (e: React.PointerEvent) => {
    if (e.pointerType !== "mouse") return;
    const g = gesture.current;
    if (g.mode !== "drag") return;
    const dx = e.clientX - g.startX;
    const dy = e.clientY - g.startY;
    if (!g.moved && Math.hypot(dx, dy) >= DRAG_THRESHOLD_PX) g.moved = true;
    const c = clampOffset(g.startTx + dx, g.startTy + dy, scale);
    setTx(c.x);
    setTy(c.y);
  };

  const onPointerEnd = (e: React.PointerEvent) => {
    if (e.pointerType !== "mouse") return;
    const g = gesture.current;
    if (g.mode !== "drag") return;
    g.mode = "none";
    setDragging(false);
    if (g.moved) dragClickPending.current = true;
    try {
      imgRef.current?.releasePointerCapture?.(e.pointerId);
    } catch {
      /* pointer capture unavailable */
    }
  };

  const onImgClick = (e: React.MouseEvent) => {
    // Clicking the image itself never closes the lightbox.
    e.stopPropagation();
    // Record whether this click was the tail end of a drag, then consume the
    // flag; onDoubleClick uses the history of the last two clicks.
    const [, prev] = lastTwoClicksDragged.current;
    lastTwoClicksDragged.current = [prev, dragClickPending.current];
    dragClickPending.current = false;
  };

  const onImgDoubleClick = () => {
    // Belt-and-braces for browsers that synthesize a dblclick from a double-
    // tap despite the preventDefault in onTouchEnd: any dblclick this close
    // to touch activity is tap-derived, and the touch path already toggled.
    if (Date.now() - lastTouchEndAt.current < 500) return;
    // A double-click where either press was actually a drag must not toggle.
    const [a, b] = lastTwoClicksDragged.current;
    if (a || b) return;
    if (scale > 1) reset();
    else setScale(2.5);
  };

  return (
    <div
      className="fixed inset-0 z-[300] flex items-center justify-center bg-black/90"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
    >
      {/* Top bar: close + download. Stop propagation so taps here don't close. */}
      <div
        className="absolute top-0 left-0 right-0 flex items-center justify-between px-4 py-3 z-10"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className="w-9 h-9 rounded-full bg-white/15 text-white flex items-center justify-center hover:bg-white/25 transition-colors"
          aria-label="Close"
        >
          <X className="w-5 h-5" />
        </button>
        <a
          href={src}
          download={downloadName}
          className="w-9 h-9 rounded-full bg-white/15 text-white flex items-center justify-center hover:bg-white/25 transition-colors"
          aria-label="Download"
        >
          <Download className="w-5 h-5" />
        </a>
      </div>

      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        ref={imgRef}
        src={src}
        alt={alt || ""}
        draggable={false}
        onClick={onImgClick}
        onTouchStart={onTouchStart}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}
        onWheel={onWheel}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerEnd}
        onPointerCancel={onPointerEnd}
        onDoubleClick={onImgDoubleClick}
        className="max-w-full max-h-full object-contain select-none touch-none"
        style={{
          transform: `translate(${tx}px, ${ty}px) scale(${scale})`,
          // No transition mid-gesture (touch pan/pinch or mouse drag) — the
          // "drag" mode covers the pointer drag; `dragging` state forces the
          // re-render at drag start/end so this style actually recomputes.
          transition: gesture.current.mode === "none" ? "transform 0.15s ease-out" : "none",
          cursor: scale > 1 ? (dragging ? "grabbing" : "grab") : "zoom-in",
        }}
      />
    </div>
  );
}
